stages:
    - build
    #- lint
    - test
    - push
    #- pushremote

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .cache

build:
    stage: build
    tags:
        - shell
    script:
        - make docker-build

#lint:
#    stage: lint
#    tags:
#        - shell
#    script:
#        - make docker-lint

test:
    stage: test
    tags:
        - shell
    script:
        - make docker-test
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

push:
    stage: push
    tags:
        - shell
    script:
        - make docker-pushlocal

#pushremote:
#    stage: pushremote
#    tags:
#        - shell
#    only:
#        refs:
#            - tags
#            - master
#            - /^release_*/
#            # - develop
#    script:
#        - make docker-pushremote
#
#pushremote-forced:
#    stage: pushremote
#    tags:
#        - shell
#    only:
#        variables:
#            - $CI_COMMIT_MESSAGE =~ /.*pushremote.*/
#    except:
#        refs:
#            - tags
#            - master
#            - /^release_*/
#            - develop
#    script:
#        - make docker-pushremote